language: java

before_install:
 - chmod +x gradlew

jdk:
  - oraclejdk8

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.gradle

script:
  - ./gradlew clean build

after_script:
  - echo $SLACK_TOKEN
notifications:
  slack: scsaci:$SLACK_TOKEN