language: java
before_install:
- chmod +x gradlew
jdk:
- oraclejdk8
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.gradle"
script:
- "./gradlew clean build"
deploy:
  provider: heroku
  app: scsaci
  api_key:
    secure: CITi2/JE/gjBTtkpcCVOXVfl5LggrLdiqo1jz7TKKKVCHmKOU3AeBwoEcSENFLfJxIXJeh71MWOhlL5tqSZaeoh2Q9LACv8Wf6HCa9Z9DcTK+cHly0bgmw4nRqjHmxWP/gEV34CldDZ3uGbObE3hwYIOTIqq1ahe0TI1rW2AAgQRnMS1s0jP8zw2L1OHSknsvbsIxo2tAMjjBRqDlKEquCc3lNl/y2pWOAJxAJPuoHRkAfjbhF8GzA5Kprdr8vDtq7LTf3frlM9+/NPP7hGZ1QwUrbIPOjy8OMI6/A/K0JvLUkg/J6HSamMLoLZbvIPjZFIjDO/8zglTrXCH971e056+9NmtAY1dHkl/TnM8moATTriW1exPyVXw2ad6DW9fdZcd3BxLDJ8p9d3hcsndj3IJBr8WIi4dXAMtnV7J9AQQMYWzLLLmbNgG2jNkBYJKu9Weh2b1HRZMoBcJE709GW6mZR7116l4wx08K1o5CFsU4EvuAmJ9/WZ2jmm9ZjqfqxSHhHD/UBKTsg7SlnLn/Sp+kGBf4xTTncbvO1paY/DLF8JTV5uLUXkSgEH5b4GkxN9aYvpm0o1Ct58xSnqKiQPcBe+olCl2qbDYF73JIrYhdzbEjggpCLED69JED9IE9cWzLn0jA1Bk2bVFIjZW/GTGxmx3jlO7b020qW9PrHQ=
notifications:
  slack:
    rooms:
      secure: VhD9kU/621fvl1LM4jyCxl3AMv0kmRJZQkIsByo6DxpG0H3yICU0s/Jag50D/f4QkzvDYvBrd9Md4asF/E8Kd7eu2OPV8wwdFKGKcCgy1Gdw6SmyNR1HkTdIGuhIkASPfyTj82omruhRk8GV8wRbenxujOGPFct1K5RDd4kVk6lSgCKqtjVeDQwCVeJWZbcLbap6I//bGQxXwdk++tIUSLsjO8qPKuz+QZCko5ngqEpgAoS9WKujpGd7Q03PqTtghxlJo/7Lu7z9DrlPHuuwn7Ysv1+twT1S2MGe4DkCT4P0Uqt4Gk301n1gFfuUkj+lxalPhMMkCLM7zmNevwCIvR8YlwYqPzTsJxoYjcTsaymodg+M4jmP2MPxLd6930Nh80KXhuIJhO8SPG5OBqWyd4tvUbDM2S+wndJ3DH+kD7lyiZ9naeN0w6EY2YV5lA0aJNVH19VB3p5GzdwXJiEtYaH9u4SCSh5MnkeZjvr23W3yPoLkEUT1TU6rysf9vt8vD0aXlRAZrWLkVK4j/PQt7Ar8zQg2V2iMb5vOfzWk07OdbQXRci1YLR1qFCrjCRsxoQ7thc08vYVhRBnRZcNZFzJJEw0OKFFXB3QRVWzXcUghX21NP5UAt6ljSzfCbVmTYlL5a5MiI6CFwtBFjMCpDikAlrFDt2fE4cTnHxMpA2A=
