language: java

before_install:
 - chmod +x gradlew

jdk:
  - oraclejdk8

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.gradle

script:
  - ./gradlew clean build

notifications:
  slack: $SLACK_ACCOUNT_TOKEN

deploy:
  provider: heroku
  api_key: 4735e264-c987-425f-b1c2-f2be6a8ec954
  app: scsaci
