language: java
before_install:
- chmod +x gradlew
jdk:
- oraclejdk8
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.gradle"
script:
- "./gradlew clean build"
deploy:
  provider: heroku
  app: scsaci
  api_key:
    secure: IXvicfIDTBrU/x8fi+WULM9gkqBf2bRektziwQL4W2Q2yy97XIQcNwYtkIZGUrZzlu4/4wvdhfgqmJcKy/5WaiGhgEgJ1c96lTg8q+oYoznvtylJ4cfyMvaQVwg80wsLYv53+6Q76PP77v/KGzP4kKpM85rgUsizF0DV3ztgiUSeDQX2xBlX/gMrn3CyM1eOAHiSGwPrbP7YloKSAIjMPh9ng4+PPOW0w7YnoOXuj6GzlR8DCoasAgUKIrTM664YsRMqoIRVW6/Q2/uUjlG0/VFnJ0dYmEJvkvEDczitfYSPCIlWN8TqU5aYR3q6BTyqzv7I9626ddF+0GUUOsp9i3SAFzLA9rC7HERwxUf7MwSV8oX9EACv48G8033ggb78M3AL+Em9q7TUHZ2NCEcFtn9yzrxCoFx1Z+xNiHlA+ULMSp9VR6eDj6C1GtVAIWxT+FbmXYf3GOq3ZSVj5iMnyYfuX7DmPIW/dJPMNsbLEN1YMx7ofQ17+U/OyN7jIn87T6+dLk77AcJmgP5tmKyhwDXqg1um5TrKmrqSKxqa534cPwkNr/j770PpH66f24TfIIRXBa4qE/Fhb70X+/ZCQDTaU0vAWwp7DiUJesezPLNxz1nH18698TznsbAyNxfEPyrbjAufiMelB0MjvtvjyNjhXkpWHIvbQCEAem1HTOQ=

notifications:
  slack:
    rooms:
      secure: L5Nfx9J8PGaldoiH2FL5vdVNWTSNMan7eRuXkAKSZbrfC3H2jknFBvEDJhPwOR6nrux8KvUO9ZY7KU7XPApU683QTZwEcvPoobBzfyeMIuawjB3Zvsuh4SoybsiDzUQx5QVuxzxOA1TVCOF50e1qzW3VPL5y1GuFrOYnYokGBM52IC67gJWT2eJIAVEpjHKmpatjH9CfqgX7UhhGvPP3eAnzri5S5S5y4mYKPQEZwd+NN4JR7ogMEy+tuR2MBkz2E1sURswne/5XRQcNCsY8vxzKhg73O9xMo9pi/QSsOZ9R9vnJBoQHuSvlE9LJI9gePq8n1q2zhs6Q/cApKhOwenKr4mtDv1WY1DBEUICy20UsOWigXcD0w8HNblDirQw02tea/c7mTRD0MTNhDM3xEWKO92CzEecbZn4xUI8Tdz8QLiOgEhFjlsoRtQD4KtkWt8Zk+odPRFi9yCDDgll2Fzndwr3iK0Mr5y1wBNZhFeTRPXCnoaHhDejJd5+EL7x36M8H6J6p0Ld0z2Xt2XHJcfdu22M7wVd5QWPXWXYaqQS856N28TK41Iyh3Ud/RcCBS+rBysVRoLKCWtkWdajBM+VIhYkh63VRnoPCQi9sU+R4VpasrSQplNBW+2bsLvp5oBQmhdUSUZ8P4JmBRshNAOIDvK30TVmE56A9+3q/Uec=
