language: java
jdk:
  - oraclejdk8

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.gradle

script:
  - sudo ./gradlew clean build

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer