language: java

before_install:
 - chmod +x gradlew

jdk:
  - oraclejdk8

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.gradle

script:
  - ./gradlew clean build

notifications:
  slack: scsaci:MmCO8MbgVKJ5pkB0Ol7Szcoe