spring:
  application:
    name: student-service
  datasource:
      initialize: false
      sql-script-encoding: UTF-8
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:func_testdb;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE
      username: ${DB_USERNAME:sa}
      password: ${DB_PASSWORD:}
#    driverClassName: org.mariadb.jdbc.Driver
#    url: jdbc:mysql://${DB_HOST:localhost}/${DB_SCHEMA:test}
  jpa:
      hibernate:
          #none, validate, update, create-drop, create
          ddlAuto: update
      show-sql: true
